// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2rKIgKtqAJBOI1PzPhLWcrW7_Ry-e0I',
    appId: '1:863466183268:web:eac7e67dee0611df1c1d71',
    messagingSenderId: '863466183268',
    projectId: 'datacollector-project',
    authDomain: 'datacollector-project.firebaseapp.com',
    databaseURL: 'https://datacollector-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'datacollector-project.appspot.com',
    measurementId: 'G-N3XSVJTR6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzWw82ZNfGMqLzbqJ5KMLS-SDgolvvtQ',
    appId: '1:863466183268:android:e30e0be7bc0102741c1d71',
    messagingSenderId: '863466183268',
    projectId: 'datacollector-project',
    databaseURL: 'https://datacollector-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'datacollector-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQUouEVmTk_32ugJpqFo6xcgpBTcSjzLM',
    appId: '1:863466183268:ios:92e743234cfbf4001c1d71',
    messagingSenderId: '863466183268',
    projectId: 'datacollector-project',
    databaseURL: 'https://datacollector-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'datacollector-project.appspot.com',
    iosClientId: '863466183268-bh5fg6trdg90tu5mh07ko5dvm9scp39l.apps.googleusercontent.com',
    iosBundleId: 'com.senselab.datacollector',
  );
}
